{{- $hasSecrets := or .Values.secrets.vaultPassphrase .Values.secrets.openaiApiKey .Values.secrets.anthropicApiKey .Values.secrets.azureOpenaiEndpoint .Values.secrets.azureOpenaiApiKey .Values.secrets.googleApiKey -}}
{{- if $hasSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phi-redactor.fullname" . }}
  labels:
    {{- include "phi-redactor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if .Values.secrets.vaultPassphrase }}
  PHI_REDACTOR_VAULT_PASSPHRASE: {{ .Values.secrets.vaultPassphrase | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiEndpoint }}
  AZURE_OPENAI_ENDPOINT: {{ .Values.secrets.azureOpenaiEndpoint | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureOpenaiApiKey }}
  AZURE_OPENAI_API_KEY: {{ .Values.secrets.azureOpenaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
